### ISSUE TITLE
Released package contains hardcoded path to /home/daniel

### ISSUE THREAD

**Issue by anmaje** [connectordb/connectordb-desktop#5]
This package for Linux is trying to run stuff I don't have and my user name is not Daniel... 
I downloaded it here https://connectordb.io/download/

```INFO[0000] Staring redis on port 6380                   
panic: Could not find executable redis-server
goroutine 1 [running]:
dbsetup.GetExecutablePath(0xcc7c5d, 0xc, 0xcc060e, 0x5)
	/home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/filetools.go:195 +0x1a8
dbsetup.(*RedisService).Start(0xc4202e7020, 0x0, 0x0)
	/home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/redis.go:54 +0xdc
dbsetup.Start(0xc420017b30, 0xc420017b30, 0x0)
	/home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/allservices.go:140 +0xa17
commands.glob..func8(0x1280180, 0xc4202c27d0, 0x1, 0x1, 0x0, 0x0)
	/home/daniel/Desktop/ConnectorDB/connectordb/src/commands/start.go:85 +0x34e
github.com/spf13/cobra.(*Command).execute(0x1280180, 0xc4202c2780, 0x1, 0x1, 0x1280180, 0xc4202c2780)
	/home/daniel/go/src/github.com/spf13/cobra/command.go:644 +0x3f2
github.com/spf13/cobra.(*Command).ExecuteC(0x127fb20, 0x0, 0x1, 0x1)
	/home/daniel/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x127fb20, 0xc420207f68, 0x0)
	/home/daniel/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/daniel/Desktop/ConnectorDB/connectordb/src/main.go:12 +0x31
2017-12-04 14:03:03,849 Logging in as jessica to http://localhost:3124
2017-12-04 14:03:03,852 Stopping database at /home/jessica/.local/share/connectordb/cdb

**Comment by dkumor** [comment]
The directories given are the directories of the source code files during compilation: I compiled them in my home directory!

The issue looks like you don't have redis installed, or ConnectorDB could not find it. Could you please share the OS you used?

If using ubuntu, making sure redis is installed can be done with the following:
```
sudo apt-get install redis-server

sudo systemctl disable redis-server.service
sudo systemctl stop redis-server.service
```
